name: TestStackIgn83
services:
    IgnFeCont:
        image: inductiveautomation/ignition:8.3
        container_name: IgnFeCont
        hostname: IgnFeHost
        ports:
            - 9088:8088
        volumes:
            - IgnFeVol:/usr/local/bin/ignition/data
        networks:
            - IgnFeNet
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command: >
            -n IgnFeGateway
            -m 2048
    IgnBeCont:
        image: inductiveautomation/ignition:8.3
        container_name: IgnBeCont
        hostname: IgnBeHost
        ports:
            - 9089:8088
        volumes:
            - IgnBeVol:/usr/local/bin/ignition/data
        networks:
            - IgnFeNet
            - IgnBeNet
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command: >
            -n IgnBeGateway
            -m 2048
volumes:
    IgnFeVol:
        name: IgnFeVol
    IgnBeVol:
        name: IgnBeVol
networks:
    IgnFeNet:
        driver: bridge
        name: IgnFeNet
    IgnBeNet:
        name: IgnBeNet
