name: TestStack2
services:
    frontend:
        image: inductiveautomation/ignition:8.3
        hostname: frontend
        ports:
            - 9988:8088
        volumes:
            - fe83-data:/usr/local/bin/ignition/data
        networks:
            - frontend
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command:
            -n frontend-gateway
            -m 2048
    backend:
        image: inductiveautomation/ignition:8.3
        hostname: backend
        ports:
            - 9989:8088
        volumes:
            - be83-data:/usr/local/bin/ignition/data
        networks:
            - frontend
            - backend
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command:
            -n backend-gateway
            -m 2048
volumes:
    fe83-data:
    be83-data:
networks:
    frontend:
    backend:
