# You can give the stack a name but it wont use the capitalization.  grrfuck
name: TestStackIgn83
services:
    IgnFeCont:
        image: inductiveautomation/ignition:8.3
        container_name: IgnFeCont
        hostname: IgnFeHost
        ports:
            - 9088:8088
        volumes:
            - IgnFeVol:/usr/local/bin/ignition/data
        networks:
            - IgnFeNet
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command: >
            -n IgnFeGateway
            -m 2048
    IgnBeCont:
        image: inductiveautomation/ignition:8.3
        container_name: IgnBeCont
        hostname: IgnBeHost
        ports:
            - 9089:8088
        volumes:
            - IgnBeVol:/usr/local/bin/ignition/data
        networks:
            - IgnFeNet
            - IgnBeNet
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command: >
            -n IgnBeGateway
            -m 2048
    MariaDbCont:
        image: mariadb:12.2.2
        container_name: MariaDbCont
        hostname: MariaDbHost
        ports:
            - 3306:3306
        volumes:
            - MariaDbVol:/var/lib/mysql
        networks:
            - IgnBeNet
        environment:
            - MARIADB_ROOT_PASSWORD=@csiToledo1
            - MARIADB_DATABASE=IgnData
            - MARIADB_USER=acsiuser
            - MARIADB_PASSWORD=@csiToledo1
volumes:
    IgnFeVol:
        name: IgnFeVol
    IgnBeVol:
        name: IgnBeVol
    MariaDbVol:
        name: MariaDbVol
networks:
    IgnFeNet:
        driver: bridge
        name: IgnFeNet
    IgnBeNet:
        driver: bridge
        name: IgnBeNet
