# You can give the stack a name but it wont use the capitalization.  grrfuck
name: TestStackIgn83
services:
    # Ignition FE gateway
    IgnFeCont:
        image: inductiveautomation/ignition:8.3
        container_name: IgnFeCont
        hostname: IgnFeHost
        ports:
            - 9088:8088
        volumes:
            # Volume for Ign data
            - IgnFeVol:/usr/local/bin/ignition/data
            # Bind mount for backup file
            - /home/jonqnash/Ignition/IgnFeGateway.gwbk:/restore.gwbk
            # Bind mount for uuid file
            - /home/jonqnash/Ignition/IgnFe_uuid.txt:/usr/local/bin/ignition/data/config/local/ignition/gateway-network/uuid.txt
            # Bind mount for metro-keystore file
            - /home/jonqnash/Ignition/IgnFe_metro-keystore.pfx:/usr/local/bin/ignition/data/config/local/ignition/gateway-network/keystore/metro-keystore.pfx
        networks:
            - IgnFeNet
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command: >
            -n IgnFeGateway
            -m 2048
            -r /restore.gwbk
    # Ignition BE gateway
    IgnBeCont:
        image: inductiveautomation/ignition:8.3
        container_name: IgnBeCont
        hostname: IgnBeHost
        ports:
            - 9089:8088
        volumes:
            # Volume for Ign data
            - IgnBeVol:/usr/local/bin/ignition/data
            # Bind mount for backup file
            - /home/jonqnash/Ignition/IgnBeGateway.gwbk:/restore.gwbk
            # Bind mount for uuid file
            - /home/jonqnash/Ignition/IgnBe_uuid.txt:/usr/local/bin/ignition/data/config/local/ignition/gateway-network/uuid.txt
            # Bind mount for metro-keystore file
            - /home/jonqnash/Ignition/IgnBe_metro-keystore.pfx:/usr/local/bin/ignition/data/config/local/ignition/gateway-network/keystore/metro-keystore.pfx
        networks:
            - IgnFeNet
            - IgnBeNet
        environment:
            - IGNITION_EDITION=standard
            - GATEWAY_ADMIN_PASSWORD=password
            - ACCEPT_IGNITION_EULA=Y
        command: >
            -n IgnBeGateway
            -m 2048
            -r /restore.gwbk
    # MariaDb database
    MariaDbCont:
        image: mariadb:12.2.2
        container_name: MariaDbCont
        hostname: MariaDbHost
        ports:
            - 3306:3306
        volumes:
            - MariaDbVol:/var/lib/mysql
        networks:
            - IgnBeNet
        environment:
            - MARIADB_ROOT_PASSWORD=@csiToledo1
            - MARIADB_DATABASE=IgnData
            - MARIADB_USER=acsiuser
            - MARIADB_PASSWORD=@csiToledo1
    # MailCatcher SMTP mail server
    MailCont:
        image: dockage/mailcatcher:0.9
        container_name: MailCont
        hostname: MailHost
        ports:
            - 1080:1080
            - 1025:1025
        networks:
            - IgnBeNet
volumes:
    IgnFeVol:
        name: IgnFeVol
    IgnBeVol:
        name: IgnBeVol
    MariaDbVol:
        name: MariaDbVol
networks:
    IgnFeNet:
        driver: bridge
        name: IgnFeNet
    IgnBeNet:
        driver: bridge
        name: IgnBeNet
